### ISSUE TITLE
A link in the footer is broken

### ISSUE THREAD

**Issue by vishrana** [fabasoad/business-card#192]
The following link in the footer is broken.

https://en.cryptobadges.io/donate/145HwyQAcv4vrzUumJhu7nWGAVBysX9jJH
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/31931163/188314622-735073ba-7a97-49ea-abe6-615ca89b1574.png">

**Comment by fabasoad** [comment]
Oh. Good catch! Thank you. Will fix it soon 🙏
